apiVersion: audit.k8s.io/v1
kind: Policy
omitStages:
  - RequestReceived
rules:
  - level: None
    users:
      - aws-lb-readvertiser
      - cloud-config-downloader
      - etcd-client
      - gardener
      - garden.sapcloud.io:system:cert-broker
      - kubelet
      - system:apiserver
      - system:cloud-controller-manager
      - system:cluster-autoscaler
      - system:kube-addon-manager
      - system:kube-aggregator
      - system:kube-apiserver:kubelet
      - system:kube-controller-manager
      - system:kube-proxy
      - system:kube-scheduler
      - system:machine-controller-manager
      - system:serviceaccount:auditlog:auditlog-garden-cm
      - system:serviceaccount:default:app-hub-controller
      - system:serviceaccount:garden:gardener-apiserver
      - system:serviceaccount:garden:gardener-controller-manager
      - system:serviceaccount:garden:gardener-dashboard
      - system:serviceaccount:garden:gardener-extension-admission-gcp
      - system:serviceaccount:garden:gardener-extension-validator-alicloud
      - system:serviceaccount:garden:gardener-extension-validator-aws
      - system:serviceaccount:garden:gardener-extension-validator-azure
      - system:serviceaccount:garden:gardener-extension-validator-openstack
      - system:serviceaccount:garden:gardener-extension-validator-vsphere
      - system:serviceaccount:garden:gardener-scheduler
      - system:serviceaccount:garden:secret-binding-distributor
      - system:serviceaccount:terminal-system:default
      - virtual-garden:client:admin
      - vpn-seed
  - level: None
    userGroups:
      - gardener.cloud:system:seeds
      - garden.sapcloud.io:monitoring
      - system:nodes
      - system:serviceaccounts:kube-system
  - level: None
    resources:
      - group: ""
        resources:
          - configmaps
          - events
          - tokenreviews
  - level: Metadata
    resources:
      - group: ""
        resources:
          - secrets
  - level: None
    verbs:
      - get
      - list
      - watch
  - level: None
    nonResourceURLs:
      - /*
  - level: None
    resources:
      - group: authorization.k8s.io
        resources:
          - localsubjectaccessreviews
          - selfsubjectaccessreviews
          - selfsubjectrulesreviews
          - subjectaccessreviews
  - level: Request
    resources:
      - group: "" # core
      - group: admissionregistration.k8s.io
      - group: apiextensions.k8s.io
      - group: apiregistration.k8s.io
      - group: apps
      - group: authentication.k8s.io
      - group: authorization.k8s.io
      - group: autoscaling
      - group: batch
      - group: certificates.k8s.io
      - group: coordination.k8s.io
      - group: extensions
      - group: metrics.k8s.io
      - group: networking.k8s.io
      - group: policy
      - group: rbac.authorization.k8s.io
      - group: scheduling.k8s.io
      - group: settings.k8s.io
      - group: storage.k8s.io