apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: cluster
    required: true
    targetType: landscaper.gardener.cloud/kubernetes-cluster

  - name: hostingCluster
    schema:
      type: object
      properties:
        namespace:
          type: string
        infrastructureProvider:
          type: string
          default:
            value: gcp

  - name: virtualGarden
    schema:
      definitions:
        scaleParams:
          type: object
            properties:
              cpu:
                type: object
                properties:
                  value:
                    type: string
                  percentage:
                    type: integer
              memory:
                type: object
                properties:
                  value:
                    type: string
                  percentage:
                    type: integer
              replicas:
                type: object
                properties:
                  value:
                    type: string
                  percentage:
                    type: integer
      type: object
      properties:
        etcd:
          type: object
          properties:
            storageClassName:
              type: string
            backup:
              type: object
              properties:
                infrastructureProvider:
                  type: string
                region:
                  type: string
                bucketName:
                  type: string
                credentialsRef:
                  type: string
            handleETCDPersistentVolumes:
              type: boolean
            hvpaEnabled:
              type: boolean
        kubeAPIServer:
          type: object
          properties:
            replicas:
              type: integer
              default:
                value: 6
            sni:
              type: object
              properties:
                hostname:
                  type: string
                dnsClass:
                  type: string
                ttl:
                  type: integer
                secretName:
                  type: string
            dnsAccessDomain:
              type: string
            gardenerControlplane:
              type: object
              properties:
                validatingWebhookEnabled:
                  type: boolean
                mutatingWebhookEnabled:
                  type: boolean
            auditWebhookConfig:
              type: object
                properties:
                  config:
                    type: string
            auditWebhookBatchMaxSize:
              type: string
            hvpaEnabled:
              type: boolean
            hvpa:
              type: object
                properties:
                  maxReplicas:
                    type: integer
                  minReplicas:
                    type: integer
                  targetAverageUtilizationCpu:
                    type: integer
                  targetAverageUtilizationMemory:
                    type: integer
                  vpaScaleUpMode:
                    type: string
                  vpaScaleDownMode:
                    type: string
                  vpaScaleUpStabilization:
                    type: object
                      properties:
                        stabilizationDuration:
                          type: string
                        minChange:
                          "$ref": "#/definitions/scaleParams"
                  vpaScaleDownStabilization:
                    type: object
                      properties:
                        stabilizationDuration:
                          type: string
                        minChange:
                          "$ref": "#/definitions/scaleParams"
                  limitsRequestsGapScaleParams:
                    "$ref": "#/definitions/scaleParams"
                  maintenanceWindow:
                    type: object
                    properties:
                      begin:
                        type: string
                      end:
                        type: string
            eventTTL:
              type: string
            oidcIssuerURL:
              type: string
            additionalVolumeMounts:
              type: array
              items:
                volumeMount:
                  type: object
                  properties:
                    name:
                      type: string
                    readOnly:
                      type: boolean
                    mountPath:
                      type: string
                    subPath:
                      type: string
                    mountPropagation:
                      type: string
                    subPathExpr:
                      type: string
            additionalVolumes:
              type: array
              items:
                volume:
                type: object
            horizontalPodAutoscaler:
              type: object
              properties:
                downscaleStabilization:
                  type: string
                readinessDelay:
                  type: string
                cpuInitializationPeriod:
                  type: string
                syncPeriod:
                  type: string
                tolerance:
                  type: string
        deleteNamespace:
          type: boolean

  - name: credentials
    description: "credentials map"
    schema:
      type: object
      additionalProperties:
        type: object
        description: "credentials"
        properties:
          type:
            type: string
          data:
            type: object
            additionalProperties:
              type: string

exports:
- name: kubeApiserverCaPem
  schema:
    type: string

- name: etcdCaPem
  schema:
    type: string

- name: etcdClientTlsPem
  schema:
    type: string

- name: etcdClientTlsKeyPem
  schema:
    type: string

- name: kubeconfigYaml
  schema:
    type: string

- name: virtualGardenEndpoint
  schema:
    type: string

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /virtual-garden-container-deployer.yaml
  name: virtual-garden-container-deployer
  type: GoTemplate

